### ISSUE TITLE
Back button is in front of create

### ISSUE THREAD

**Issue by jensMF** [quicksc0p3r/simplecounter#33]
When I try to add a lable or counter the back button is in front of the create button. So instead of creating something the creation is aborted. This does not happen in landscape mode.

**Comment by quicksc0p3r** [comment]
What device are you using?
Are you using gestures or 3-button navigation?
Are you using the release APK or did you build yourself from upstream?

**Comment by jensMF** [comment]
Sorry, seems like I was in a hurry ^^'
My Device has a 6'' 1080x2160 display and (unfortunately) still android 10.
I am using the three button navigation and the f-droid version.
Here is a screenshot: 
![Screenshot_20240520-224946_Simple_Counter](https://github.com/quicksc0p3r/simplecounter/assets/1620034/64203e4e-ff45-4e1c-a528-2c7a6dd803f3)


I hope this helps otherwise please tell me what is missing.

**Comment by quicksc0p3r** [comment]
Thanks for the extra information. I will debug this further.

**Comment by quicksc0p3r** [comment]
Interestingly, the issue is not present in the latest upstream build with edge-to-edge enabled.
However, on the current release build, the action buttons are obscured by the navigation bar on Android 10 and below (the issue is not present on Android 11 and above).
This issue will not be present in the next release build, which will have edge-to-edge enabled.

**Comment by jensMF** [comment]
Yes it's fixed. Thank you! :-)
